// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.10.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'error.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'slicing.dart';
import 'utils.dart';

// These functions are ignored because they are not marked as `pub`: `flat_samples_into_ndarray`, `new`, `u8_color_array_to_f32_norm`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<YoloModelSession>>
abstract class YoloModelSession implements RustOpaqueInterface {
  double get iouThreshold;

  BigInt get numLabels;

  double get sliceIouThreshold;

  set iouThreshold(double iouThreshold);

  set numLabels(BigInt numLabels);

  set sliceIouThreshold(double sliceIouThreshold);

  static Future<YoloModelSession> fromMemory({
    required VecU8Wrapper bytes,
    required BigInt numLabels,
    required double iouThreshold,
    required double sliceIouThreshold,
  }) => RustLib.instance.api.crateApiModelYoloModelSessionFromMemory(
    bytes: bytes,
    numLabels: numLabels,
    iouThreshold: iouThreshold,
    sliceIouThreshold: sliceIouThreshold,
  );

  Future<List<YoloEntityOutput>> slicedInference({
    required VecU8Wrapper image,
    required int imageWidth,
    required int imageHeight,
    required bool keepOriginal,
    required List<SliceInputParams> sliceOptions,
  });
}
